### ISSUE TITLE
v11

### ISSUE THREAD

**Issue by brunocalado** [EthanJWright/foundryvtt-importer#106]
Please, update to v11! Tks

**Comment by Sisimshow** [comment]
While it would be nice that this was officially updated, it does seem to work on V11 with only a minor tweak to the module.json

If you open it in a text editor and look for the line "maximum": "10" and change it to "maximum": "11" you will be able to load it and, at least from my limited testing, it does seem to work. Can't say if there are any smaller issues though.

**Comment by EthanJWright** [comment]
Ah my bad, updating now! Was between campaigns so missed this
