### ISSUE TITLE
Promblems importing Adventurer's League statblocks

### ISSUE THREAD

**Issue by cs96and** [EthanJWright/foundryvtt-importer#18]
First of all, great module!  This will save me tons of prep time!

I'm trying to import a statblock from the Adventurer's League Oracle of War module DDAL-EB-10.  Here's an image of the statblock, and the copy n' pasted text version...

![image](https://user-images.githubusercontent.com/898086/151220652-fc31e172-f91a-44b8-87e2-d6f817603825.png)

```
Big Bara
Medium humanoid (warforged), neutral evil
Armor Class 18 (natural armor, Imposing Majesty)
Hit Points 117 (18d8 + 36)
Speed 30 ft.
STR
 DEX
 CON
 INT
 WIS
 CHA
14 (+2)
 17 (+3)
 15 (+2)
 13 (+1)
 16 (+3)
 18 (+4)
Saving Throws Con +6, Wis +7
Skills Perception +7, Survival +7
Damage Immunities poison
Condition Immunities charmed, frightened, poisoned
Senses darkvision 60 ft., passive Perception 17
Languages Common
Challenge 9 (5,000 XP)
Imposing Majesty. Big Bara adds her Charisma bonus to her AC
(included above).
Warforged Resilience. Big Bara is immune to disease and magic
can’t put her to sleep.
Actions
Multiattack. Big Bara makes two attacks, either with her
shortsword or armbow.
Shortsword. Melee Weapon Attack: +7 to hit, reach 5 ft., one
target. Hit: 6 (1d6 + 3) piercing damage plus 13 (3d8) poi-
son damage.
Armbow. Ranged Weapon Attack: +7 to hit, range 30/120 ft.,
one target. Hit: 10 (2d6 +3) piercing damage plus 13 (3d8) poi-
son damage.
Poisonous Cloud (2/Day). Poison gas fills a 20-foot-radius
sphere centered on a point Big Bara can see within 50 feet of
her. The gas spreads around corners and remains until the start
of Big Bara’s next turn. Each creature that starts its turn in the
gas must succeed on a DC 16 Constitution saving throw or be
poisoned for 1 minute. A creature can repeat the saving throw
at the end of each of its turns, ending the effect on itself on
a success.
```

After importing, the actor looks like this...

![image](https://user-images.githubusercontent.com/898086/151220932-696539e5-1a3d-4559-8de4-d09cd2519553.png)

There are a few problems with it...

1. The ability scores are all 0, apart from Cha, which is 14 instead of 18.
2. The saving throws are wrong for Con and Wis
3. The perception and survival skills are wrong
4. None of the damage immunities, Condition immunities, senses or languages have been imported.
5. Poisonous Cloud is missing completely
6. Creature type and alignment are missing
7. The armbow does not roll an attack roll, it just rolls damage
8. I am unable to edit the "Shortsword" and "Warforged Resilience" items.  Simply opening these items and then closing the window is enough to trigger the error.  If I attempt to make changes, then they are lost after re-opening the item.
![image](https://user-images.githubusercontent.com/898086/151221919-b94c2097-42fe-4726-a916-438593b24f8f.png)

**Comment by cs96and** [comment]
I also just noticed that the poison damage is missing from the Shortsword and Armbow damage rolls

**Comment by EthanJWright** [comment]
Wonderful thanks so much for sharing, I'm able to duplicate your error and I have a very strong suspicion I know what is causing it, I should be able to get it patched tonight!

**Comment by EthanJWright** [comment]
@cs96and The issues you described should have been resolved in this commit: bf22c2ce4f78264baaa022eebd6505927a5bd296

Update to version 0.2.2 and let me know if your problems are fixed!

One note: I think the error thrown when trying to edit weapons is a more pervasive bug, I've noticed it in a few other modules that create monsters as well. I'm going to spend some time investigating it but wanted to get all of the other concerns addressed as quickly as possible. If everything else is fixed, I'll close this issue out and open another issue for that specifically.

**Comment by cs96and** [comment]
Thanks!

It might be worth asking on Discord about the embedded ID problem.

**Comment by EthanJWright** [comment]
I'm going to spend a little more time looking into it and if I can't figure it out I'll tag in discord, I'm going to close this, feel free to open another ticket if you have issues.

Thanks again for the detailed ticket and extra data, part of my goal for publishing this was to start getting a variety of other input to harden my solution, so it's very much appreciated.

**Comment by cs96and** [comment]
Sorry only just got round to testing the new version.  Works great now, apart from one minor thing... I'll submit another report.  Thanks.
