### ISSUE TITLE
If a statblock contains unexpected sense restriction the parsing fails

### ISSUE THREAD

**Issue by Mastecker** [EthanJWright/foundryvtt-importer#25]
**Describe the bug**
actors.process.ts:714 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
[Detected 1 package: foundry-vtt-content-parser]
    at actors.process.ts:714:39
    at Array.forEach (<anonymous>)
    at getSenses (actors.process.ts:712:13)
    at textToActor (actors.process.ts:835:13)
    at txtRoute (actor.ts:6:17)
    at importActorForm.processActorInput [as _handler] (actor.ts:36:5)
    at importActorForm._updateObject (importActorForm.ts:26:10)
    at importActorForm._onSubmit (foundry.js:3853:18)

**To Reproduce**
Spythronar Sac
Tiny aberration, unaligned
Armor Class 5
Hit Points 1 (1d4 – 1)
Speed 0 ft.
STR DEX CON INT WIS CHA
1 (–5) 1 (–5) 8 (–1) 1 (–5) 3 (–4) 1 (–5)
Condition Immunities blinded, charmed, deafened,
exhaustion, frightened, paralyzed, petrified, poisoned,
prone, restrained, unconscious
Senses tremorsense 10 ft. (blind beyond this radius),
passive Perception 6
Languages —
Challenge 0 (10 XP) Proficiency Bonus +2
False Appearance. The spythronar sac appears to be
a tangled ball of string, twigs, and dirt. Someone who
can see the sac can identify it with a successful DC 15
Intelligence (Arcana or Nature) check.
Fragile. A creature who enters the spythronar sac’s
space must succeed on a DC 10 Dexterity saving throw,
or the sac is destroyed.
Lightning Release. When the spythronar sac is
destroyed, it releases lightning in a 10-foot radius. A
creature who destroyed the sac by entering its space
receives no saving throw. Other creatures in that area
must succeed on a DC 10 Dexterity saving throw or
take 4 (1d8) lightning damage. Each spythronar swarm
and web in this area instead gains advantage on its
next attack roll.
Shocking Birth. When a spythronar sac takes lightning
damage from a source other than another spythronar,
it hatches, transforming into a spythronar swarm with
half the normal hit points. This swarm rolls initiative and
enters the combat.

**Expected behavior**
Either the restriction gets integrated or it could be skipped atm

**Screenshots**

**Additional context**
Also if the monster doesnt has skills it will  throw an error as well but parses nevertehless.

**Comment by EthanJWright** [comment]
Thanks for reporting this, it should be fixed in 0.2.6. 
This stat block helped me uncover a few other bugs as well.
Let me know if you have any other issues!
