### ISSUE TITLE
Batch markdown to compendium

### ISSUE THREAD

**Issue by HallsOfRust** [EthanJWright/foundryvtt-importer#27]
Great project! I saw that the future plans in the readme include markdown as a source and support for exporting to a compendium. I would like to express my interest for that use-case.

I currently have a few homebrew markdown files of monsters (formatted as [tetra-cube or Homebrewery](http://tetra-cube.com/dnd/dnd-statblock.html) does), which is useful because I can keep them in source control. At the moment I use a hacked-together script to convert them to compendiums of actors, but since this project seems more polished I'd love to switch over. Would you be interested in a contribution for this offline processing case? Any suggestions for how this should look?

Thanks!

**Comment by EthanJWright** [comment]
Thanks! That sounds like a great use cases I would be interested in working on.

If you write code and feel like working on the project, you can always make a PR if you get it to a point where you have it working and I'd be happy to review it.

Alternatively, you can share any example data with me and that would make it much easier for me to add tests and build it into my module. I can't promise how quickly I can get to it but it shouldn't be too long.

Feel free to drop anything here, or you can hit me up on discord (GabenMessiah#0551) for offline communication on the issue.

**Comment by EthanJWright** [comment]
I'll message you on discord, but to keep the update public - I refactored the Actor API so it should be easy to add new parsers, and I added [developer docs](https://github.com/EthanJWright/foundryvtt-importer#contributing-to-the-codebase)

**Comment by EthanJWright** [comment]
Hey - going to clean up and close this for now, if you end up getting the time to finish your work and open a PR for your fork, I'm happy to review!
