### ISSUE TITLE
Support Actions

### ISSUE THREAD

**Issue by HallsOfRust** [EthanJWright/foundryvtt-importer#29]
**Is your feature request related to a problem? Please describe.**
Currently both actions and features are parsed as features. Features are something like the following:
> ***Spider Climb.*** The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.

Whereas actions are something like the following:
> ***Bite.*** *Melee Weapon Attack:* +8 to hit, reach 5 ft., one creature. *Hit:* 23 (4d8 + 5) piercing damage.

**Describe the solution you'd like**
Wherever possible, the parser should distinguish between plain features and action-features.

An action may look as complicated as:
> ***Web (Recharge 5–6).*** *Ranged Weapon Attack:* +8 to hit, range 30/60 ft., one
creature. *Hit:* The target is restrained by webbing. As an action, the restrained target can
make a DC 14 Strength check, bursting the webbing on a success. The webbing can also be
attacked and destroyed (AC 10; hp 5; vulnerability to fire damage; immunity to bludgeoning,
poison, and psychic damage).

Key things to support:
* Name
* Description
* Type (melee, ranged, other)
* To-hit
* Damage
* Damage type (slashing, fire)

Optional extras:
* Associated saving throws
* Recharging
* Lair / legendary actions

**Comment by EthanJWright** [comment]
A lot of this is done through 'item parsing', as foundry exposes all of these elements through the Item interface. I had this logic at a different layer of the stack, and hadn't flushed out the parsing logic. 

In v0.2.8 I've updated the structures to parse actor item data at the same level so different parers can handle items differently, and updated the typing and parsing logic for items. It should address most of the concerns you've listed here. 

The Item parsers aren't quite as well flushed out as the actor parsors, so feel free to open PRs with changes or open an issue if there are problems with the way things are currently exposed.

Thanks for the input!
