### ISSUE TITLE
Parsing of Standard FVTT Tables to RollTables

### ISSUE THREAD

**Issue by SabreRunner** [EthanJWright/foundryvtt-importer#31]
**Is your feature request related to a problem? Please describe.**
It's so hard to get a table that is not balanced.

**Describe the solution you'd like**
The ability to copy a table (with two columns, a die description, and a title) from a standard Foundry journal entry and parse that into a rolltable.

**Describe alternatives you've considered**
Tried all the methods described in the front page but couldn't get a non-balanced table.

![image](https://user-images.githubusercontent.com/10673434/154100493-39a4f2b1-e9de-4a0a-a14a-3e153d80b5d3.png)

**Comment by EthanJWright** [comment]
Makes sense and definitely don't have support for this currently, I'll look into adding it! It shouldn't be too difficult.

**Comment by EthanJWright** [comment]
Would you mind providing the steps for how you get these tables into a journal entry? What is the source / how can I emulate this table for testing purposes?

**Comment by EthanJWright** [comment]
@SabreRunner I believe version v0.2.9 #33 should have this working the way you were hoping. If things are still not working as expected, please open a new ticket with copy/pasted input that I can add tests for.

Thanks for opening the issue!
