### ISSUE TITLE
Parsing Issue

### ISSUE THREAD

**Issue by NateSaloon** [EthanJWright/foundryvtt-importer#34]
I appear to be having an issue with parsing a few different stat blocks, such as the one below.
```
Kip, the "Warlord"
Medium Humanoid (kobold)
Armor Class 18 (breastplate, haste potion)
Hit Points 49 (9d8+9)
Speed 60 feet while hasted; 30 feet otherwise
STR DEX CON INT WIS CHA
7(-2) 15(+2) 16(+3) 8(-1) 7(-2) 12(+1)
Senses darkvision 60 ft., passive Perception 8
Languages Draconic
Challenge 1 (200 XP)
Hasted. The "warlord" has advantage on Dexterity saving
throws and his speed is doubled. His AC is increased by
2.
Enlarged. The "warlord's" size is increased to medium
and his attacks deal an extra 1d4 damage.
Borrowed Power. The warlord has consumed a potion of
growth and a potion of haste. At the end of each of his
turns, roll a d6. A result of 1 indicates that the effect of
one of the potions has expired.
Pack Tactics. The kobold has advantage on an attack roll
against a creature if at least one of the kobold's allies is
within 5 feet of the creature and the ally isn't
incapacitated.
Sunlight Sensitivity. While in sunlight, the kobold has
disadvantage on attack rolls, as well as on Wisdom
(Perception) checks that rely on sight.
Actions
Multiattack. The "warlord" makes two scimitar of speed
attacks.
Scimitar of Speed. Melee Weapon Attack: +6 to hit, reach
5 ft., one target. Hit: 8 (1d6+4) slashing damage, plus 2
(1d4) slashing damage while enlarged.
```

When the monster block text is copied and pasted for importing, nothing happens. Below is the error code in the browser console.

![Screenshot (367)](https://user-images.githubusercontent.com/100549097/155920163-fd9b3bee-3392-48d5-867a-936f28393bc7.png)

Everything is up to date and I have tried turning off all modules except this one, however, the error persists.

**Comment by EthanJWright** [comment]
Hi, definitely an error in this module, looks like it's not grabbing the alignment properly. I'll add a test with this input and get it sorted shortly, thanks for sharing!

**Comment by NateSaloon** [comment]
Glad to hear it! Yep, adding an alignment appears to allow the text to parse, however, it appears to not recognize the ability scores in this type of format resulting in unchanged ability scores in the character sheet.

**Comment by EthanJWright** [comment]
Hey!  The stat block you posted should be working now with #36 (version 0.2.10) - this helped me uncover some problems:
- alignment shouldn't be required
- previously, there wasn't support for ability blocks that didn't have a space between the ability and the modifier, i.e. 7(-2)
- there were some issues with parsing senses

I've patched all of these using your stat block.

Thanks for sharing and feel free to open another issue if you still have problems or find other issues!
