### ISSUE TITLE
Making this system agnostic

### ISSUE THREAD

**Issue by danil0man** [EthanJWright/foundryvtt-importer#35]
**Is your feature request related to a problem? Please describe.**
Hello, I was looking at your module and it looks great, but I notice this is only for dnd. Would it be possible to make this system agnostic

**Describe the solution you'd like**
Been able to use this module independent of system

**Describe alternatives you've considered**

**Additional context**
I would love to import tables from pdf and csv to my games. But since I don't play dnd this module is not showing in my games. Please can you at least make the table part agnostic. Thx you

**Comment by EthanJWright** [comment]
Hmmm good point, I'll add comments to the configuration to indicate what features are 5E specific, and then remove the system restriction
