### ISSUE TITLE
XMl import support 

### ISSUE THREAD

**Issue by Boigm** [EthanJWright/foundryvtt-importer#41]
hi i have xml 5e compendiums files and was wondering if you would consider adding support for xml files being imported

**Comment by EthanJWright** [comment]
Hey - mind adding any more details around this?

How are you generating the XML files?
What is the hope for the user interaction & final results? (i.e. is this an actor import, that generates multiple actors, etc)

**Comment by Boigm** [comment]
Mostly just classes and features from the fight club app

**Comment by EthanJWright** [comment]
Did a bit of looking into the data structures - it's a heavier lift than I have time for considering it's not a workflow I would ever use. I'd be happy if anyone wanted to contribute to this project to enable it, but I don't think I'll have time soon to do it myself. Thanks for opening the issue!
