### ISSUE TITLE
Journal Importer Order Reversed

### ISSUE THREAD

**Issue by MtnDew35** [EthanJWright/foundryvtt-importer#42]
**Describe the bug**
When multiple values are present, they get imported into Foundry in reverse order

**To Reproduce**
`[
    {
        "value": "Setting the Scene ",
        "tag": "h2",
        "notes": [
            {
                "value": "When everyone is ready to begin, read the following boxed text aloud: ",
                "tag": "p"
            },
            {
                "value": "You\u2019re returning home after a successful rescue mission into the Mournland. With you are the surviving members of the Gray Dogs, the salvage crew you were sent to rescue. Two of them are dragging a strange device through the mud; the Oracle of War , which you unearthed from the ruins of Kalazart.  A flickering pillar of light briefly pierces the sky from a hilltop ahead. The Mournland is deathly quiet and your every step and breath echoes through the valley. Atop the hill, a stone cottage slumps like frozen corpse. ",
                "tag": "p"
            },
            {
                "value": "Now go around the table and ask each player to describe their character as they trudge through the Mournland. When they\u2019re done, give everyone inspiration . ",
                "tag": "p"
            }
        ],
        "children": [
            {
                "value": "The Gray Dogs ",
                "tag": "h3",
                "notes": [
                    {
                        "value": "The characters travel with the following NPCs, who all share the scout stat block. The scavengers are grateful to be rescued and eager to get home. ",
                        "tag": "p"
                    },
                    {
                        "value": "\u2022 Durvo Tellis (male dwarf) \u2022 Kalli Alran (female human) \u2022 Nella Halthorn (female halfling) \u2022 Sprocket (warforged) ",
                        "tag": "p"
                    },
                    {
                        "value": "If the players have the Hard Call legacy event, Durvo Tellis was left behind at the Fireweave Bazaar and does not feature in this adventure. ",
                        "tag": "p"
                    }
                ],
                "children": []
            },
            {
                "value": "Durvo Tellis (DER-voh TELL-us) ",
                "tag": "h3",
                "notes": [
                    {
                        "value": "Neutral male dwarf scavenger Durvo is a pale-skinned 165-year-old dwarf and a veteran scavenger. He wears a patch over one milky, dead eye and has a sour attitude for anything that isn\u2019t getting down to business gathering treasure.  Motivation: Survival. Durvo needs cash to stay alive and feed himself.  Mannerisms: Durvo ignores people and questions not worth his time. Fun is frivolous, and frivolous doesn\u2019t get you paid. Quote: \u201c Enough jawing. Time to get to work. \u201d",
                        "tag": "s1"
                    }
                ],
                "children": []
            },
            {
                "value": "Kalli Alran (KAL-ee ALL-run) ",
                "tag": "h3",
                "notes": [
                    {
                        "value": "Neutral female human scavenger Kalli is a brown-skinned Cyran human in her forties who was visiting Sharn on the Day of Mourning. She has a friendly personality and has made it a personal mission to recover artifacts from her homeland. Motivation: Loyalty. The few friends Kalli has left are worth fighting for: but cross her and she\u2019ll hold a grudge like nobody\u2019s business.  Mannerisms: Kalli is always smiling. Quote: \u201c No one lives forever, eh? \u201d ",
                        "tag": "s1"
                    }
                ],
                "children": []
            },
            {
                "value": "Nella Halthorn (NEL-uh HALL-thorn) ",
                "tag": "h3",
                "notes": [
                    {
                        "value": "Neutral female halfling scavenger Nella is a tan halfling in her twenties from Sharn. She has a sharp wit and is quick to make a joke.  Motivation: Wealth. Nella is trying to raise enough money to pay off her brother\u2019s gambling debts to the Boromar Clan, a criminal syndicate in Sharn.  Mannerisms: Nella often sniffs when she talks. Quote: \u201c Easy as tumbledown pie. \u201d ",
                        "tag": "s1"
                    }
                ],
                "children": []
            },
            {
                "value": "Sprocket ",
                "tag": "h3",
                "notes": [
                    {
                        "value": "Neutral warforged scavenger Sprocket is a 15-year-old warforged who worked for House Cannith as an assistant to several artificers. When the Treaty of Thronehold was signed, Sprocket decided to use his knowledge of magic items to make a living scouring the Mournland for treasure.  Motivation: Discovery. Sprocket hopes to find meaning for his life inside the Mournland.  Mannerisms: Sprocket\u2019s right arm occasionally malfunctions and vibrates violently. Quote: \u201c Doesn\u2019t look so hard to me. \u201d",
                        "tag": "s1"
                    },
                    {
                        "value": "Not for resale. Permission granted to print or photocopy this document for personal use only",
                        "tag": "s2"
                    },
                    {
                        "value": ".",
                        "tag": "s1"
                    },
                    {
                        "value": "DDAL-EB-03 Where the Dead Wait v1.0 6",
                        "tag": "s2"
                    }
                ],
                "children": []
            },
            {
                "value": "The  Oracle of War",
                "tag": "h3",
                "notes": [
                    {
                        "value": "Give the players Handout 1: Oracle of War . This information represents everything they\u2019ve learned so far about the device. ",
                        "tag": "p"
                    }
                ],
                "children": []
            }
        ]
    }
]`

```txt
```

**Expected behavior**
Proper order, preferably with a new line between them.

**Screenshots**
![JSON](https://user-images.githubusercontent.com/31868584/165362545-ae0ecf95-a260-4c30-8894-6bfd2be822fc.png)
![Imported](https://user-images.githubusercontent.com/31868584/165362587-ea0ed159-d273-40b1-8785-86d53e500a99.png)

**Comment by EthanJWright** [comment]
Ahh yeah I remember debugging this at one point, and my solution may have not been perfect. I'll take a look at this when I get a chance, shouldn't be too long. Thanks for reporting! The journal importing stuff was definitely on the jankier side of this plugin
