### ISSUE TITLE
Other Language Support

### ISSUE THREAD

**Issue by fylson** [EthanJWright/foundryvtt-importer#45]
Is it possible to support other languages? German for example?

**Comment by EthanJWright** [comment]
Going to close this issue for now as the localization is required for matching all the elements of the raw input, as well as the user interface, and it would be an incredible amount of effort to do those translations to German. I may work in some generic interfaces so it's easier to extend the module to other languages by contributors, but if I have time for that I will make sure to publish the feature in the CHANGE LOG and communicate it in the developer docs. 

Thanks for opening the issue!
