### ISSUE TITLE
Module Directory Issue

### ISSUE THREAD

**Issue by justinthejaguar** [EthanJWright/foundryvtt-importer#62]
This module doesn't appear to be downloadable from the FVTT module directory. I was able to get the manifest link off the module.json, but I thought I should let you know. A very good module btw. Thank you.

![Screen Shot 2022-08-21 at 7 55 15 AM](https://user-images.githubusercontent.com/38022481/185789706-aa6de32a-bff3-4391-a3fa-8f62e0761cea.png)

**Comment by EthanJWright** [comment]
> This module doesn't appear to be downloadable from the FVTT module directory. I was able to get the manifest link off the module.json, but I thought I should let you know. A very good module btw. Thank you.
> 
> 
> 
> ![Screen Shot 2022-08-21 at 7 55 15 AM](https://user-images.githubusercontent.com/38022481/185789706-aa6de32a-bff3-4391-a3fa-8f62e0761cea.png)
> 
> 

Oh shoot I just have fudged a link - thanks I'll update that!

**Comment by EthanJWright** [comment]
Okay should have updated the module.json -- much appreciate you opening an issue!
