### ISSUE TITLE
Can you make it parse MCDM monsters?

### ISSUE THREAD

**Issue by SabreRunner** [EthanJWright/foundryvtt-importer#67]
They are roughly the same but some different layout choices, along with the addition of a role, confuses the parser very much, requiring a lot of cleanup.

**Comment by SabreRunner** [comment]
There is a [Free Preview](https://files.mcdmproductions.com/FleeMortals/FleeMortalsPreview.pdf) available where you can see how they look different.

**Comment by PsykotikDragon** [comment]
> Need some examples posted here to look into it - can't promise a timeline but I'd imagine I could get it working!
> 
> If you want to keep the examples private you can hit me up over email or discord

![image](https://user-images.githubusercontent.com/52022617/197167799-be1e65e5-c7ef-4432-b0d6-5d1d238589f7.png)

Here's a screenshot from their free preview linked by SabreRunner.

**Comment by EthanJWright** [comment]
Had a few different things I needed to patch up so it took a while but this should all be good now!
