### ISSUE TITLE
Using Other System than d&d5E for Journal Creation not possible

### ISSUE THREAD

**Issue by shadows-eye** [EthanJWright/foundryvtt-importer#69]
**Describe the bug**
The Import Button is missing for Journals only, no error messages

**To Reproduce**
Install the Dark Eye System and load the Module, the button to import will be available but not for Journals.

**Expected behavior**
The Button to appear beneath Journal Browser in the Dark Eye System

**Screenshots**
![image](https://user-images.githubusercontent.com/71041904/201517754-f9b521f8-13a5-48ab-a18e-38c809f85204.png)

**Additional context**
Thanks for any support on this.

**Comment by EthanJWright** [comment]
Think the issue is that it's off by default, you had to enable it in the config. Just changed that behavior since I think I've added enough features for the journal parser to be useful. Lmk if you still have an issue.
