### ISSUE TITLE
Is it possible to add custom Templates for Parsing?

### ISSUE THREAD

**Issue by ChromeMystic** [EthanJWright/foundryvtt-importer#80]
**Is your feature request related to a problem? Please describe.**
my group will start playing shadow of the demon lord, and there are no real importers for that System yet. Enterying Data manually in Foundry is very time consuming.

**Describe the solution you'd like**
A way to create custom Templates for Items and Actors would be great. Unless you plan support for other Systems anyway.

**Describe alternatives you've considered**
Sadly I haven't found any other than Data Toolbox, and that looks a lot more complicated compared to your solution.

**Additional context**
I can provide more information, if you are interested in supporting other systems. If you don't have the time that is of course fine.

**Comment by EthanJWright** [comment]
Unfortunately it's quite complicated to parse stat blocks and then convert them into the foundry JSON model, so it's not something I'm looking to make overly generic and automatically compatible with all systems.

If you wanted to make a PR to add the foundry conversions and add tweaked parsers if necessary, I would certainly test it and merge it, but it isn't something I have the time or necessarily the capability to do in a highly generic adaptable way.
