### ISSUE TITLE
Failure to Parse

### ISSUE THREAD

**Issue by igotsmeakabob11** [EthanJWright/foundryvtt-importer#81]
**Describe the bug**
Failure on parsing, at health. Possibly another module interfering but not sure which? I have been able to successfully use this in the past!

**To Reproduce**
Provide example data that you are inputting into the parser which will recreate the error. 
Place the data in the code block please.

```Uncaught (in promise) Error: undefined. Could not parse actor, errors: [Error: Could not parse element: "Parser error for [parseHealthWTC] -> Error: Could not parse health from line: (1d6 + 1)"]
[Detected 1 package: foundry-vtt-content-parser]
    at tryActorParse (typeGuardParserRunners.ts:214:9)
    at textToActor (index.ts:8:10)
    at txtRoute (handleInput.ts:8:17)
    at importActorForm.processActorInput [as _handler] (handleInput.ts:38:5)
    at importActorForm._updateObject (importGenericForm.ts:25:10)
    at importActorForm._onSubmit (foundry.js:5916:18)
```

**Expected behavior**
Proper import :) 

**Screenshots**
attached 
**Additional context**

**Comment by EthanJWright** [comment]
Can you provide the input please? Then I can replicate with a test and patch the code!

**Comment by igotsmeakabob11** [comment]
Korsoth Vastikan
Medium aberration, chaotic
ARMOR CLASS 16 (studded leather)
HIT POINTS 78 (12d8 + 24)
SPEED 40 ft.
STR DEX CON INT WIS CHA
13
(+1)
18
(+4)
14
(+2)
11
(+0)
13
(+1)
12
(+1)
SAVING THROWS Dex +7, Wis +4
SKILLS Acrobatics +7, Deception +4, Investigation +3, Perception +4, Stealth +7, Survival +4
DAMAGE RESISTANCES psychic
CONDITION IMMUNITIES charmed, petrified
SENSES darkvision 60 ft., passive Perception 14
LANGUAGES Deep Speech, Primordial
CHALLENGE 6 (2,300 XP)
Everchanging Changers. The Court of All Flesh
are beings of pure chaos. Because their minds
are pure disorder, they cannot be driven mad or
charmed and any attempts to magically compel
their behavior fails.
Formless Shape. Vastikan is immune to any spell
or effect that would alter his form.
Formkiller. If Vastikan hits a target with three
arrows in one round, the target must make
a DC 12 Constitution saving throw or lose its
native form. Roll on the Reincarnation table to
determine the target’s new form. The target
reverts to its original form after 1 hour.1 A target
that succeeds on its saving throw becomes
immune to Formkiller for 24 hours.
Actions
Multiattack. Vastikan makes four
longbow attacks.
Longbow. Ranged Weapon Attack: +7 to hit,
range 150/600 ft., one target. Hit: 8 (1d8 + 4)
piercing damage.
Shortsword. Melee Weapon Attack: +7 to
hit, reach 5 ft., one target. Hit: 8 (1d8 + 4)
piercing damage.

**Comment by EthanJWright** [comment]
Should be working now, the parser wasn't expecting health or ac to be in all caps

**Comment by igotsmeakabob11** [comment]
Awesome! Thank you. Love the module
