### ISSUE TITLE
NPC import issues and possible inspiration for code

### ISSUE THREAD

**Issue by maxobremer** [EthanJWright/foundryvtt-importer#83]
Tried using ChatGPT to create a statblock and basically had a hard time, then tried to import it using https://github.com/jbhaywood/5e-statblock-importer and it went a lot better, maybe that module and its code could be used as inspiration to improve this module.
After reloading foundry (because I enabled 5e statblock importer) and having disabled import npc, I found all the attacks and features of the failed to import statblock in my item directory, which wasn't ideal.

Also tried importing a spell and it became a potion instead, thought that could be cause spells are a future feature?
(the spell btw:
Dazing Blast

2nd-level evocation
Casting Time: 1 action
Range: 60 feet
Components: V, S
Duration: Instantaneous
A wave of forceful energy leaves your palms and travels towards your target. Make a spell attack against a creature. If you hit the target, they take 2d6 force damage and must succeed at a Constitution saving throw or become dazed until the end of their next turn.

At Higher Levels. When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d6 for each spell slot above 2nd.

**Comment by EthanJWright** [comment]
Do you have an example of the ChatGPT statblock that is working better with 5e importer but failing w/ foundryvtt-importer?

That's a great module, if it is working for you feel free to keep using it! Not really a goal of mine to read through and copy the code, happy keeping this the tool that it is which is a bit more 'generally try to parse anything, handle things hackily if necessary'.

I'll take a look at the spell, I've had some weirdness working w/ the foundry API for those so more examples help me improve the module.

**Comment by maxobremer** [comment]
this is one example:

Giggles the Jerbeen Clown

Small humanoid (jerbeen), chaotic neutral

Armor Class 10

Hit Points 5 (1d6 + 1)

Speed 30 ft.

STR 8 (-1) DEX 12 (+1) CON 12 (+1) INT 10 (+0) WIS 10 (+0) CHA 14 (+2)

Skills Performance +4, Sleight of Hand +3

Senses passive Perception 10

Languages any one language (typically Common)

Challenge 1/8 (25 XP)

Comic Timing. Giggles has advantage on Charisma (Performance) checks made to entertain an audience.

ACTIONS

Silly Squirt. Ranged Weapon Attack: +3 to hit, range 20/60 ft., one target. Hit: 2 (1d4) bludgeoning damage.

Joke Book. Giggles can use an action to distract one creature within 30 ft. with a joke or silly trick. The creature must succeed on a Wisdom saving throw (DC 12) or have disadvantage on attack rolls and ability checks until the end of their next turn.



statblock 5e importer also doesnt do it perfect but everything except the silly squirt attack is imported, whereas foundry content parcer/importer fails completely
