### ISSUE TITLE
Parsing Failure Question

### ISSUE THREAD

**Issue by TombExplorer1997** [EthanJWright/foundryvtt-importer#87]
Hello I just Rectently added this module and while it works very good I on Importing most of the useful Information
It fails to Import the Dice rolls of Weapon Attacks and other dice rolling Features.
I am trying to import a monster frok the Grim Hollow Campaign guide for 5e and while the Stats are Importer correctly the Attack rolls and other Features are not present.
Is this an Error or just not a Feature of a Module?

**Comment by EthanJWright** [comment]
Would you mind including the text you're using so I can verify if it's working how I would expect in my environment?

**Comment by TombExplorer1997** [comment]
No Problem,I am using the Newest Version 2.4 on Foundry Version 10,Build 286 on dnd 5e 2.12. I am copying from a PDF on Foxit PDF Reader

<html>
<head><style>

</style></head><body>

<span class="fontstyle0">s</span><span class="fontstyle0" style="font-size:11pt;">hiFting </span><span class="fontstyle0">h</span><span class="fontstyle0" style="font-size:11pt;">uLK<br></span><span class="fontstyle2">Large aberration, any alignment<br></span><span class="fontstyle3">Armor Class </span><span class="fontstyle4">16 (natural armor)<br></span><span class="fontstyle3">Hit Points </span><span class="fontstyle4">168 (16d10 + 80)<br></span><span class="fontstyle3">Speed </span><span class="fontstyle4">30 ft.<br></span><span class="fontstyle3" style="color:rgb(129,29,47);">STR DEX CON INT WIS CHA<br></span>

20 (+5)	 10 (+0)	 20 (+5) 9 (–1) Skills Perception +4 | 11 (+0) 6 (-2)
-- | --


<span class="fontstyle3">Senses </span><span class="fontstyle4">darkvision 60 ft., passive Perception 14<br></span><span class="fontstyle3">Languages </span><span class="fontstyle4">understands one language but can’t speak<br></span><span class="fontstyle3">Challenge </span><span class="fontstyle4">9 (5,000 XP) </span><span class="fontstyle3">Proficiency Bonus </span><span class="fontstyle4">+4<br></span><span class="fontstyle6">Aberrant Wound. </span><span class="fontstyle4">If a creature other than an<br>undead or a construct takes damage from the shifting<br>hulk’s attacks, the creature must succeed on a DC 17<br>Constitution saving throw or lose 5 (2d4) hit points at the<br>start of each of its turns due to an aberrant wound. This<br>damage is cumulative. A creature can take an action to<br>staunch the wound, ending this effect with a successful<br>DC 15 Wisdom (Medicine) check. The wound also closes<br>if the target receives magical healing.<br></span><span class="fontstyle6">Vicious Critical. </span><span class="fontstyle4">When the shifting hulk scores a<br>critical hit with an attack, it can roll the attack’s<br>damage dice three times instead of twice.<br></span><span class="fontstyle6">Fast Healing. </span><span class="fontstyle4">While at half its hit points or fewer, the<br>shifting hulk regains 10 hit points at the start of each of<br>its turns. This trait doesn’t function while the hulk has<br>0 hit points.<br></span><span class="fontstyle6">Shapechanger. </span><span class="fontstyle4">The shifting hulk can use an action or<br>a bonus action to polymorph into a form that resembles<br>its Small or Medium humanoid appearance before<br>it became a horror. Its statistics are the same in each<br>form. Any equipment it is wearing or carrying isn’t<br>transformed. It reverts to its true Large form if it dies.<br></span><span class="fontstyle0" style="font-size:12pt;">a</span><span class="fontstyle0" style="font-size:8pt;">CtiOns<br></span><span class="fontstyle6">Multiattack. </span><span class="fontstyle4">The shifting hulk makes two attacks and<br>uses frightening attacks.<br></span><span class="fontstyle6">Claw. </span><span class="fontstyle2">Melee Weapon Attack: </span><span class="fontstyle4">+9 to hit, reach 5 ft., one target.<br></span><span class="fontstyle2">Hit: </span><span class="fontstyle4">19 (4d6 + 5) slashing damage and Aberrant Wound.<br></span><span class="fontstyle6">Spine. </span><span class="fontstyle2">Ranged Weapon Attack: </span><span class="fontstyle4">+9 to hit, range 30/60 ft.,<br>one target. </span><span class="fontstyle2">Hit: </span><span class="fontstyle4">18 (3d8 + 5) piercing damage and<br>Aberrant Wound.<br></span><span class="fontstyle6">Frightening Attacks. </span><span class="fontstyle4">Each creature of the shifting<br>hulk’s choice within 30 feet of the hulk and aware of it<br>must succeed on a DC 12 Wisdom saving throw or become frightened for 1 minute. A creature can repeat the<br>saving throw at the end of each of its turns, ending the<br>effect on itself on a success. If a creature’s saving throw is<br>successful or the effect ends for it, the creature is immune<br>to the hulk’s frightening attacks for the next 24 hours or<br>until it scores a critical hit, whichever comes first.</span> 
<br style=" font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; ">

</body>
</html>

**Comment by EthanJWright** [comment]
I imported it, and it's working about how I would expect. It set up die rolls for claw, which is the only ability I can interpret as an attack with a die roll associated.

If you would expect other things to behave differently, could you perhaps point me to a standard 5e monster that has it's abilities configured in the way you would expect, so I have something I can base the behavior on?

Or maybe you can explain the behavior you would expect so I can see if I can replicate it in foundry.

Thanks!

**Comment by TombExplorer1997** [comment]
Thank you for responding, I tried some other Standart 5e Statblocks from the Basic rules,Like the Young red Dragon but again the same problem,none of the dice roll abilities seem to work,I took the Statblock directly from the SRD.
It does say that the Compatibility risk for verified version 10.285 and I am Using 10.286,Could that be the Problem?

**Comment by EthanJWright** [comment]
Everything described in these is passing as best as I can detect in v0.2.45, if you have any other issues please open another ticket and be very specific about the exact spell in the example that is failing and what it is missing!
