### ISSUE TITLE
AC = Armor Class

### ISSUE THREAD

**Issue by stgreenb** [EthanJWright/foundryvtt-importer#88]
Can you teach the Parser that AC = Armor class? 

In [this module](https://www.dmsguild.com/product/360148/Shadows-Under-Emystrell-5E), the author has slightly deviated from the standard block and one of the items tripping the parser is the author has chosen "AC" instead of Armor Class. 

Sample block below: 

Dire Squirrel
Medium beast, unaligned
AC: 12
Hit Points: 24 (3d8)
Speed: 50 ft., climb 40 ft.
STR 14 (+2) DEX 15 (+2) CON 10 (+0) INT 3 (-4) WIS 14 (+2) CHA 7 (-2)
Skills: Perception +4, Stealth +6
Senses: passive Perception 14
Challenge 1/4 (50 XP)
Keen Smell. The dire squirrel has advantage on Wisdom (Perception) checks 
that rely on smell.
Pounce. If the dire squirrel moves at least 20 ft. straight toward a creature and 
then hits it with a claw attack on the same turn, that target must succeed on a 
DC 12 Strength saving throw or be knocked prone. If the target is prone, the 
panther can make one bite attack against it as a bonus action.
Actions
Bite. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: (1d6 + 2) 
piercing damage.
Claw. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: (1d4 + 2) 
slashing damage.

**Comment by EthanJWright** [comment]
Yep should be very doable, sorry just saw this, I'll add that soon
