### ISSUE TITLE
Parse didn't work: nothing happens

### ISSUE THREAD

**Issue by c4ll4d0ct0r** [EthanJWright/foundryvtt-importer#90]
So when I paste my text in and hit "Okay," it doesn't work for this specific statblock: nothing happens, there is no actor created. I have done a few other statblocks without issue, this is the first time I am having a problem. Here is the statblock that is giving me trouble:

Scorching Shadow
Medium dragon, lawful evil

Armor Class: 15 (natural armor)
Hit Points: 45 (6d8 + 18)
Speed: 30 ft., fly 60 ft.

STR: 16 (+3)
DEX: 14 (+2)
CON: 16 (+3)
INT: 8 (-1)
WIS: 13 (+1)
CHA: 10 (+0)

Skills: Stealth +4
Senses: Darkvision 60 ft., passive Perception 11
Languages: Draconic

Challenge Rating: 2 (450 XP)

Actions:

Multiattack: Scorching Shadow makes two attacks: one with its bite and one with its steampunk tail.

Bite: Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d10 + 2) piercing damage.

Steampunk Tail: Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) bludgeoning damage.

Fire Bolt: Ranged Spell Attack: +4 to hit, range 120 ft., one target. Hit: 10 (3d6) fire damage.

Burning Hands: Scorching Shadow unleashes a 15-foot cone of fire. Each creature in that area must make a DC 13 Dexterity saving throw, taking 14 (4d6) fire damage on a failed save, or half as much damage on a successful one.

Reactions:

Flame Absorption: Scorching Shadow can absorb a fire spell cast at it and regain hit points equal to the spell's level.

Legendary Actions:

Scorching Shadow can take 2 legendary actions, choosing from the options below. Only one legendary action option can be used at a time, and only at the end of another creature's turn. Scorching Shadow regains spent legendary actions at the start of its turn.

Fire Breath: Scorching Shadow exhales a 15-foot cone of fire. Each creature in that area must make a DC 13 Dexterity saving throw, taking 14 (4d6) fire damage on a failed save, or half as much damage on a successful one.

Tail Swipe: Scorching Shadow makes a tail attack.

Lingering Flames: Scorching Shadow causes flames to continue to burn on any creatures or objects that were previously affected by its fire spells or attacks, dealing an additional 1d6 fire damage at the start of their turn. The flames last until the creature or object takes an action to extinguish them.

**Comment by EthanJWright** [comment]
There's a lot about the shape of this stat block that I haven't seen come up before:
- the stats are printed in a unique way, with a colon after each stat, and having all the data for a stat per line
- Everything that is generally a period in most stat blocks is a colon in this one
- There are extra colons in places I haven't seen before, like after 'Hit Points'

if you clean those things up, it parses relatively well. Would you mind sharing where you got this from? Trying to determine whether it's worth spending the time to add handling for all of those things into this tool, or if it's not something that will be common enough to support.

Thanks!

**Comment by c4ll4d0ct0r** [comment]
It is indeed oddly formatted now that you mention it. The origin of the statblock is Chat GPT! Thanks for your response.

**Comment by EthanJWright** [comment]
Ah I use chat gpt to do loads of stat blocks too, and it's like 50/50 whether it generates a stat block that can cleanly plug in. If you go to Application -> toggle developer tools on an error you will generally see the things that it didn't like.

I'd recommend just hand tweaking the chat gpt stat blocks to make them look more normal, or try to adjust the prompt a bit to get it to spit out more standard blocks.

I did catch a few bugs with this though, so thanks for commenting. Let me know if anything else comes up, going to close this for now!
