### ISSUE TITLE
Failed Monster Import (Spells do not import correctly)

### ISSUE THREAD

**Issue by nyxalteria** [EthanJWright/foundryvtt-importer#92]
**Describe the bug**
Content parser fails to add the limited  daily usage for spells and just results into spell slots for several different statblocks. I've tried various formatting fixes and changing "spellcasting" to "Innate Spellcasting" for this specific statblock and it does not help.

**To Reproduce**
Provide example data that you are inputting into the parser which will recreate the error. 
Place the data in the code block please.

```Aarakocra Talon of Syranita
Medium Humanoid (Aarakocra), Typically Neutral Good
Armor Class 13
Hit Points 84 (13d8 + 26)
Speed 20 ft., fly 50 ft.
STR DEX CON INT WIS CHA
10 (+0) 16 (+3) 14 (+2) 11 (+0) 17 (+3) 11 (+0)
Skills Nature +6, Perception +9, Stealth +9, Survival +9
Senses passive Perception 19
Languages Aarakocra, Auran
Challenge 5 (1,800 XP) Proficiency Bonus +3
Dive Attack. If the aarakocra is flying and dives at least 30 feet
straight toward a target and then hits it with a melee weapon attack,
the attack deals an extra 7 (2d6) damage to the target.
Actions
Multiattack. The aarakocra makes two Talon attacks or uses Lancing
Wind twice.
Talon. Melee Weapon Attack: +6 to hit, reach 5 ft., one target.
Hit: 5 (1d4 + 3) slashing damage plus 4 (1d8) lightning damage.
Lancing Wind. Ranged Spell Attack: +6 to hit, range 120 ft., one
target. Hit: 12 (2d8 + 3) force damage. If the target is a Large or
smaller creature, it must succeed on a DC 14 Strength saving throw
or be knocked prone.
Spellcasting. The aarakocra casts one of the following spells using
Wisdom as the spellcasting ability (spell save DC 14, +6 to hit with
spell attacks):
At will: light, guidance, thaumaturgy, word of radiance
2/day each: cure wounds, call lightning
1/day each: beacon of hope, conjure elemental (air), freedom of
movement, ice storm
Bonus Actions
Fury of Syranita (3/Day). The aarakocra causes its melee or ranged
weapon attacks to magically deal an extra 7 (2d6) lightning or
thunder damage to a target on a hit. This benefit lasts until the end of
the turn.
Legendary Actions
The aarakocra can take 3 legendary actions, choosing from the
options below. Only one legendary action option can be used at a time
and only at the end of another creature's turn. The aarakocra regains
spent legendary actions at the start of its turn.
Attack. The aarakocra makes a Talon attack or uses Lancing Wind.
Cast a Spell (Costs 2 Actions). The aarakocra uses Spellcasting.
Wings of Syranita (Costs 2 Actions). The aarakocra beats its wings
and summons friendly winds from Syranita. Each enemy creature
within 20 feet of the aarakocra must succeed on a DC 14 Dexterity
saving throw or take 13 (3d8) bludgeoning damage, pushed up
to 10 feet away from the aarakocra, and be knocked prone. On a
successful save, a creature takes half as much damage and isn't
pushed or knocked prone.
```

**Expected behavior**
I expected the content parser to be able to take the daily usages for spells and apply those to the statblock, its clearly listed out in the statblock how many usages each spell has, but it totally ignores that.

**Additional context**
Has done this with several different statblocks by different publishers, I've had to manually input the spell usages for each spell.

**Comment by nyxalteria** [comment]
To be clear this is what I was expecting:
![image](https://user-images.githubusercontent.com/92659516/231892316-ada8c6ce-af1d-4624-9925-597808008ead.png)
This is what I am getting:
![image](https://user-images.githubusercontent.com/92659516/231892333-d157ef41-7c06-4d38-9931-0e15e367dd6a.png)
It's not automatically setting up the limited daily usages, some statblocks it accounts for that and some it doesn't. I've tried changing the text to say Innate Spellcasting and various formatting fixes, but neither of those things work.

**Comment by EthanJWright** [comment]
Thanks for this, great information provided - spells are super weird to parse. Thanks for providing a stat block it doesn't work for, that will help me harden the module. Will give it a go when I get a sec!

**Comment by nyxalteria** [comment]
Here's another statblock where the spells didn't import at all, I'm not sure if its due to how the feature is named, or what, but 15+ spells are failing to import.

Aboleth Overseer
Huge Aberration, Typically Lawful Evil
Armor Class 19 (natural armor)
Hit Points 273 (26d12 + 104)
Speed 10 ft., swim 40 ft.
STR DEX CON INT WIS CHA
24 (+7) 9 (-1) 18 (+4) 20 (+5) 18 (+4) 18 (+4)
Saving Throws Con +11, Int +12, Wis +11
Skills Arcana +19, History +19, Perception +18
Senses darkvision 120 ft., passive Perception 28
Languages Deep Speech, telepathy 120 ft.
Challenge 21 (33,000 XP) Proficiency Bonus +7
Amphibious. The aboleth can breathe air and water.
Greater Spell Penetration. When the aboleth casts a spell and is
interrupted by an enemy's counterspell, treat the spell's level as 5
levels higher.
Legendary Resistance (3/Day). If the aboleth fails a saving throw, it
can choose to succeed instead.
Mucous Cloud. While underwater, the aboleth is surrounded by
transformative mucus. A creature that touches the aboleth or that
hits it with a melee attack while within 5 feet of it must succeed
on a DC 19 Constitution saving throw. On a failure, the creature
is diseased for 1d4 hours. The diseased creature can breathe only
underwater.
Probing Telepathy. If a creature communicates telepathically with
the aboleth, the aboleth learns the creature's greatest desires if the
aboleth can see the creature.
Actions
Multiattack. The aboleth makes four Tentacle attacks.
Tentacle. Melee Weapon Attack: +14 to hit, reach 10 ft., one target.
Hit: 18 (2d10 + 7) bludgeoning damage and the target is grappled
(escape DC 17). If the target is a creature, it must succeed on a
DC 19 Constitution saving throw or become diseased. The disease
has no effect for 1 minute and can be removed by any magic that
cures disease. After 1 minute, the diseased creature's skin becomes
translucent and slimy, the creature can't regain hit points unless
it is underwater, and the disease can be removed only by heal or
another disease-curing spell of 6th level or higher. When the creature
is outside a body of water, it takes 6 (1d12) acid damage every 10
minutes unless moisture is applied to the skin before 10 minutes
have passed.
Tail. Melee Weapon Attack: +14 to hit, reach 10 ft., one target.
Hit: 23 (3d10 + 7) bludgeoning damage.
Enslave (3/Day). The aboleth targets one creature it can see
within 30 feet of it. The target must succeed on a DC 20 Wisdom
saving throw or be magically charmed by the aboleth until the
aboleth dies or until it is on a different plane of existence from the
target. The charmed target is under the aboleth's control and can't
take reactions, and the aboleth and the target can communicate
telepathically with each other over any distance.
Whenever the charmed target takes damage, the target can repeat
the saving throw. On a success, the effect ends. No more than once
every 24 hours, the target can also repeat the saving throw when it is
at least 1 mile away from the aboleth.
Fling. One Large or smaller object held or creature grappled by
the aboleth is thrown up to 60 feet and knocked prone. If a thrown
target strikes a solid surface, the target takes 3 (1d6) bludgeoning
damage for every 10 feet it was thrown. If the target is thrown at
another creature, that creature must succeed on a DC 22 Dexterity
saving throw or take the same damage and be knocked prone. If the
aboleth uses multiattack, it can use its Fling in place of one of its
Tentacle attacks.
Spellcasting (Psionics). The aboleth casts one of the following
spells, requiring no material components and using Intelligence as
the spellcasting ability (spell save DC 20):
At will: hypnotic pattern, invisibility, phantasmal force
3/day each: hallucinatory terrain (as an action), major image
2/day each: phantasmal killer, project image
1/day each: mirage arcane (as an action), psychic scream, weird,
plane shift (self only)
Legendary Actions
The aboleth can take 3 legendary actions, choosing from the options
below. Only one legendary action option can be used at a time and
only at the end of another creature's turn. The aboleth regains spent
legendary actions at the start of its turn.
Enslave. The aboleth uses Enslave, if available.
Tail Swipe. The aboleth makes one Tail attack.
Psychic Drain (Costs 2 Actions). One creature charmed by the
aboleth takes 28 (8d6) psychic damage, and the aboleth regains hit
points equal to the damage the creature takes.
Cast a Spell (Costs 3 Actions). The aboleth uses Spellcasting.

**Comment by EthanJWright** [comment]
All of these will become unit tests! Thanks and I'll hopefully get all of this turned around in a few days if nothing comes up

**Comment by EthanJWright** [comment]
Everything described in these is passing as best as I can detect in v0.2.45, if you have any other issues please open another ticket and be very specific about the exact spell in the example that is failing and what it is missing!

**Comment by nyxalteria** [comment]
I'm not sure if its cause of the version I'm on (10.291) of foundry and the latest version of d&d 5e but the fixes are not present, and I've updated the module to the most recent version. The stat blocks are having the same issue. (It's also showing a compatibility warning for 10.285)
![image](https://user-images.githubusercontent.com/92659516/233320274-653d82cd-2e2a-4ecc-95f4-ad41c68d9860.png)
