### ISSUE TITLE
Ranged Weapon Attacks and Actions are Parsed Incorrectly

### ISSUE THREAD

**Issue by Maedie** [EthanJWright/foundryvtt-importer#95]
**Describe the bug**
The module parses Ranged Weapon Attacks, Melee/Ranged Spell Attacks, and all Actions as Features. These features do not include the ability to roll for attacks, damage, saving throws, etc.

**To Reproduce**

```
Cherva Glist, Right-Hand Not-Man 
Medium Humanoid, Chaotic Evil
Armor Class 13 (light)
Hit Points 129
Speed 35 ft.
STR 12 (+1) DEX 16 (+3) CON 18 (+4) INT 19 (+4) WIS 18 (+4) CHA 19 (+4)
Saving Throws Strength +5, Dexterity +7, Constitution +8
Skills Acrobatics +7, Deception +8, Perception +8, Persuasion +8
Damage Resistances necrotic, poison
Senses passive Perception 14
Languages Common
Proficiency Bonus +4
Initiative +2
TRAITS
Indoctrinated Creso. When Cherva is reduced to 0 hit points and is not healed within 1 minute, his body is destroyed. He reforms in the Antipathy within the next 1d4 days.
Wicked Worm. Cherva has a burrowing speed of 45 ft.  
ACTIONS
Rapier of Mercy. Melee Weapon Attack: +7 to hit, reach 5 ft., two targets. Hit: 16 (2d8+7) slashing damage.
Transmuted Rock Worm. Ranged Weapon Attack: +7 to hit, range 30 ft., two targets. Hit: 10 (1d10+5) bludgeoning damage and 6 (1d6+3) acid damage.
Transmogrify (2/2, C). Cherva targets a limb of a creature within reach. The targeted creature must make a DC 16 Constitution saving throw or take 23 (3d12+4) necrotic damage as their body is warped and manipulated against their will. The creature takes half damage on a success. While Cherva maintains concentration:
	• Upper Limb: The target has disadvantage on attack rolls OR the target deals half damage. 
	• Lower Limb: The target has disadvantage on Dexterity saving throws OR the target's movement is halved.
Unnatural Force (1/day). Cherva directs intense transmutative force in a 60 ft. line, 5 ft. wide, directly in front of him. All creatures within the area must make a DC 15 Dexterity saving throw or take 57 (10d6+22) necrotic damage. If a target is reduced to 0 hit points with this ability, they automatically fail one death saving throw.
BONUS ACTIONS
Squirmy Worm. Cherva can Disengage or Dash as a bonus action. The Dash includes his burrow speed.
```

**Expected behavior**
I would expect the Ranged Attack to be parsed as a ranged attack in a similar manner to the Melee Attack. I would also expect the Actions to be formatted as Actions, with the ability to roll Saving Throws and Damage Rolls from the text pop-out.

**Screenshots**
![ErrorStatblock_Cherva](https://user-images.githubusercontent.com/91714442/232262103-09f2882a-834b-428d-8e4f-69b0bf5008e3.png)

**Additional context**
Hi there! I've had this issue since updating the module to the latest version and thought I'd flag it. I'm unsure what's causing it, and haven't received any error messages. Is there a different way I should format my Ranged Weapon Attacks and Actions that allows for more reliable parsing?

**Comment by EthanJWright** [comment]
Ahhh okay maybe when I eased up on the requirements for features, more things are falling through, let me take a closer look at the changes and see if I can fix it!

**Comment by EthanJWright** [comment]
Hopefully patched a lot of problems with the feature parsing, reworked a lot of code, think it's behaving a bit more how you would expect with v0.2.44 - let me know if there are still issues!

**Comment by Maedie** [comment]
Hey! Just got the chance to test this out. I put in a test statblock and it worked fantastically - thank you so much! Aside from Melee Spell Attacks and Ranged Spell attacks, which are not parsed at all, everything parses as expected. I feel Spell Attacks are negligible anyway, as it's an easy fix to convert them over. Again, thank you so much, and I have a test statblock if you ever need me to try something out on my end again :)
