### ISSUE TITLE
Compatibility issue? / Bug fixes are not present

### ISSUE THREAD

**Issue by nyxalteria** [EthanJWright/foundryvtt-importer#99]
**Describe the bug**
Bugs fixed described in previous opened issue (https://github.com/EthanJWright/foundryvtt-importer/issues/92) are not present, the exact same things are happening, possible compatibility issues? I'm on foundry 10.291 and its throwing a compatibility warning for 10.285

I am on the latest version of the 5e system. 
![image](https://user-images.githubusercontent.com/92659516/233325806-59490a7c-ea71-40b0-bc47-e6a5ad077d89.png)

**Comment by EthanJWright** [comment]
Would you mind providing a single monster block, and then a description of maybe one spell that isn't working and the exact elements that aren't working about it?

I tried to work through all of the data in the last one by hand and it was all looking right to my eyes

**Comment by nyxalteria** [comment]
That uh, would explain things, is it possible to make it pull from the compendiums? (and deprioritize srd compendiums specifically, because I have automation set up for spells and stuff like that)

**Comment by nyxalteria** [comment]
I know another stat block importer does something similar to pull from compendiums but I don't think that statblock importer receives fixes or updates frequently

**Comment by EthanJWright** [comment]
Yeah I think I remember seeing one doing that, was going to explore the API and see if I could find any examples in other modules, I'll do my best but no promises for quick turn around 😅

**Comment by nyxalteria** [comment]
Fair enough, I appreciate the response.

**Comment by EthanJWright** [comment]
I think I'm on to something, hopefully should have a feature update in tonight, or in the next few days :eyes:

**Comment by EthanJWright** [comment]
Alright, it as a doozy but I believe #92 and this issue should have been added as a feature for v0.2.46
Patched in with #100 

Open another if you find issues, but think it's working as intended now!
